server:  
  port: ${PORT:3333}

eureka:  
  client:
    serviceUrl:
      defaultZone: http://192.168.0.101:8761/eureka
      #defaultZone: http://discovery-service:8761/eureka
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true


# The "defaultZone" is a magic string fallback value that provides the service URL for any client that does not express a preference